# Generated by Django 3.2.13 on 2022-05-22 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('heading', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('visibility', models.BooleanField(verbose_name='Видимость')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2022, 5, 22, 15, 57, 49, 952657))),
                ('views_count', models.IntegerField(verbose_name='Просмотры')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liking', models.IntegerField(blank=True, choices=[(1, 'like'), (0, 'neutral'), (-1, 'dislike')], default=0, null=True, verbose_name='Оценка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='article.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='rating_unique'),
        ),
    ]
